Add files via upload
stops playe rfrom getting kncoked throggh the walls but this issue occurs (fixed by chaining line to       player.handle_collisions(Enemy.active_enemies, walls)
File "c:\Users\salma\Desktop\COMPSCIPROJECT\main.py", line 74, in <module>
    player.handle_collisions(Enemy.active_enemies)
TypeError: Player.handle_collisions() missing 1 required positional argument: 'walls'
PS C:\Users\salma\Desktop\COMPSCIPROJECT>