failed attempt at adding projectile collisons
ImportError: cannot import name 'Enemy' from partially initialized module 'enemy' (most likely due to a circular import) (c:\Users\salma\Desktop\COMPSCIPROJECT\enemy.py)
https://gyazo.com/88a792a8e8c6a737560e895932f41bc6